import type { Dict } from './i18n';

/** Simplified Chinese dictionary — mirrors the EN structure exactly. */
export const zh: Dict = {
  nav: {
    services: '服务项目',
    areas: '服务区域',
    reviews: '客户评价',
    estimate: '即时报价',
    commercial: '商业合作',
    phone: '致电调度',
  },
  hero: {
    eyebrow: '持证保险 · 万锦及约克区',
    titleA: '搬家、清运、',
    titleB: '四季维护，一站到底。',
    sub: '住宅搬家、交房深度清洁、垃圾清运、庭院养护及商业铲雪 —— 调度中心位于万锦，准时交付，从不失约。',
    ctaPrimary: '住宅即时估价',
    ctaSecondary: '商业合作 / 供应商账户',
    stats: [
      { v: '2,400+', l: '完成订单' },
      { v: '100%', l: '准时完成率' },
      { v: '< 90 分钟', l: '紧急调度响应' },
    ],
  },
  badges: {
    cgl: '$500万商业综合责任险',
    cvor: 'CVOR 认证车队',
    wsib: 'WSIB 合规员工保障',
    ontime: '100% 准时保证',
  },
  services: {
    eyebrow: '五大业务线，一支负责任的团队。',
    title: '全周期物业服务',
    sub: '从拿钥匙那天到交房那天 —— 以及中间的每一个季节。',
    items: [
      {
        id: 'moving',
        title: '住宅与办公室搬迁',
        desc: '厢式货车 + 毛毯包裹保护，拆装复位一站式服务。公寓、独立屋、办公室搬迁均可承接。',
        price: '$395 起',
      },
      {
        id: 'cleaning',
        title: '入住 / 交房深度清洁',
        desc: '通过房东与物业验收的深度清洁 —— 电器、五金、瓷砖缝隙、柜体内外全覆盖。',
        price: '$260 起',
      },
      {
        id: 'junk',
        title: '垃圾清运与遗产清理',
        desc: '皮卡 + 拖斗组合作业，地下室、遗产房屋、装修垃圾快速清空，走前打扫干净。',
        price: '$275 起',
      },
      {
        id: 'yard',
        title: '庭院季节养护',
        desc: '春季开园、秋季落叶清运、绿篱花坛养护，支持包年订阅。',
        price: '$250 起',
      },
      {
        id: 'snow',
        title: '铲雪与融雪盐服务',
        desc: '降雪 24 小时内响应，车道、步道、商业停车场全覆盖，含撒盐与防冰处理。',
        price: '每季 $480 起',
      },
    ],
  },
  estimator: {
    eyebrow: '60秒快速估价',
    title: '即时估价器',
    sub: '三步完成。无需先留邮箱 —— 价格区间先出，联系方式后留。',
    stepOf: '第 {n} 步 / 共 3 步',
    chooseService: '您需要什么服务？',
    chooseVolume: '工作量规模',
    contact: '精确报价发送到哪里？',
    services: {
      moving: '搬家搬运',
      cleaning: '深度清洁',
      junk: '垃圾清运',
      snow: '铲雪 / 庭院',
    },
    movingOptions: [
      { id: '1', label: '一房 / 开间' },
      { id: '2', label: '两房' },
      { id: '3', label: '三房' },
      { id: '4', label: '四房以上 / 办公室' },
    ],
    cleaningOptions: [
      { id: '1', label: '一房 / 开间' },
      { id: '2', label: '两房' },
      { id: '3', label: '三房' },
      { id: '4', label: '四房以上 / 商业' },
    ],
    junkOptions: [
      { id: '0.25', label: '¼ 拖斗容量' },
      { id: '0.5', label: '½ 拖斗容量' },
      { id: '1', label: '整拖斗' },
      { id: '2', label: '两车以上 / 遗产清理' },
    ],
    snowOptions: [
      { id: 'small', label: '小型车道（1–2辆车）' },
      { id: 'medium', label: '双车位车道 + 步道' },
      { id: 'large', label: '大型地块 / T字路口' },
      { id: 'commercial', label: '商业广场 / 公寓' },
    ],
    volumeLabel: '请选择规模',
    postalLabel: '邮政编码',
    postalHint: '约克区邮编前缀：L3P、L3R、L4B、L6A…',
    nameLabel: '姓名',
    emailLabel: '电子邮箱',
    phoneLabel: '电话',
    notesLabel: '还有什么需要我们了解的？（选填）',
    next: '继续',
    back: '返回',
    submit: '获取精确报价',
    submitting: '提交中…',
    rangeLabel: '此类工作的一般区间',
    firmQuote: '调度团队将在 2 个工作小时内给您锁定一口价。',
    successTitle: '已收到您的请求。',
    successBody: '报价请求已进入调度队列，2 个工作小时内会与您电话或邮件联系。',
    another: '再估一单',
    disclaimer: '仅为参考区间 —— 最终价格以现场或视频勘察为准。',
    errors: {
      required: '此项为必填',
      email: '请输入有效邮箱',
      phone: '请输入有效电话',
      postal: '格式如 L6A 1A1',
      outside: '超出约克区范围 —— 我们或许仍可服务，提交后确认。',
    },
    selectService: '请先选择服务',
    selectVolume: '请先选择规模',
  },
  gallery: {
    eyebrow: '作业实拍',
    title: '前后对比',
    sub: '拖动滑块 —— 来自万锦及约克区真实作业记录。',
    cases: [
      { title: '于比弗溪遗产房屋清运', before: '前 —— 两拖斗杂物', after: '后 —— 打扫干净' },
      { title: '万锦装修后清洁', before: '前 —— 石膏粉尘', after: '后 —— 交房标准' },
      { title: '旺市商业停车场', before: '前 —— 积雪14厘米', after: '后 —— 早5:30撒盐完毕' },
    ],
  },
  reviews: {
    eyebrow: '300+ 评价，平均 4.9 / 5',
    title: '业主与物业管理的选择',
    items: [
      {
        quote: '团队八点整到达，家具全部包裹保护，交房清洁一次通过验收。他们已经进入我们的长期供应商名单。',
        name: 'D. Whitfield',
        role: '物业管理经理，康山',
      },
      {
        quote: '地下室杂物中午前全部清空 —— 两拖斗，墙面无损伤，连车库都扫了。价格公道，全程省心。',
        name: 'M. Chen',
        role: '业主，万锦',
      },
      {
        quote: '周末帮我们完成办公室搬迁，周一早上 40 个工位全部就绪。这就够了。',
        name: 'S. Okafor',
        role: '运营负责人，旺市',
      },
    ],
  },
  dualCta: {
    residentialTitle: '家庭客户',
    residentialBody: '一口价搬家、清洁与季节套餐。60秒出参考价，2个工作小时内锁定精确报价。',
    residentialCta: '住宅即时估价',
    commercialTitle: '物业公司与企业客户',
    commercialBody: '供应商账户：保险证书（COI）备档、WSIB 合规、暴雪优先响应、组合物业月度合并账单。',
    commercialCta: '发起商业合作（RFP）',
    commercialNote: '欢迎组合物业铲雪与绿化年度合同。',
  },
  areas: {
    eyebrow: '调度中心：万锦',
    title: '约克区全域服务',
    sub: '主城区 90 分钟内紧急响应。北约克和士嘉堡交界社区亦可安排。',
    stats: { drive: '分钟平均调度', jobs: '完成订单', fsa: '覆盖邮编前缀' },
    viewPage: '查看城市页面',
  },
  footer: {
    tagline: '万锦及约克区搬家、清洁与物业维护服务。用专业服务，让生活更轻松。',
    servicesTitle: '服务项目',
    areasTitle: '服务区域',
    contactTitle: '联系方式',
    hoursLabel: '营业时间',
    rights: '版权所有。',
    licensed: '持证全保险运营 · CVOR #00000000',
  },
};
