import type { Dict } from './i18n';

/** Simplified Chinese dictionary — mirrors the EN structure exactly. */
export const zh: Dict = {
  nav: {
    services: '服务项目',
    areas: '服务区域',
    reviews: '客户评价',
    estimate: '即时报价',
    commercial: '商业合作',
    phone: '致电调度',
  },
  hero: {
    eyebrow: '持证保险 · 万锦及约克区',
    titleA: '搬家、清洁、',
    titleB: '四季维护，一站到底。',
    sub: '住宅搬家、入住/交房清洁与垃圾清运、铲雪及庭院养护 —— 调度中心位于万锦，准时交付，从不失约。',
    ctaPrimary: '住宅即时估价',
    ctaSecondary: '商业合作 / 供应商账户',
    stats: [
      { v: '2,400+', l: '完成订单' },
      { v: '100%', l: '准时完成率' },
      { v: '< 90 分钟', l: '紧急调度响应' },
    ],
  },
  badges: {
    cgl: '$500万商业综合责任险',
    cvor: 'CVOR 认证车队',
    wsib: 'WSIB 合规员工保障',
    ontime: '100% 准时保证',
  },
  services: {
    eyebrow: '四大业务线，一支负责任的团队。',
    title: '全周期物业服务',
    sub: '从拿钥匙那天到交房那天 —— 以及中间的每一个季节。',
    items: [
      {
        id: 'moving',
        title: '搬家服务',
        desc: '本地全程搬家，也提供纯人工装卸。包装、搬运、驾车、摆放，公寓、独立屋、办公室均可承接。',
        price: '$395 起',
      },
      {
        id: 'cleanup',
        title: '入住/搬后清洁 · 垃圾清运',
        desc: '一次预约全程搞定——深度清洁每个角落，清运所有垃圾杂物，让房间达到验收或交钥匙标准。',
        price: '$350 起',
      },
      {
        id: 'snow',
        title: '铲雪与撒盐服务',
        desc: '每次降雪后24小时内响应，车道、人行道、商业停车场铲雪撒盐，含冰面管理。',
        price: '每季 $420 起',
      },
      {
        id: 'yard',
        title: '庭院绿化清洁维护',
        desc: '春季清理、秋季落叶、草坪修剪、树篱花坛——全年按计划维护，四季整洁美观。',
        price: '$250 起',
      },
    ],
  },
  estimator: {
    eyebrow: '60秒快速估价',
    title: '即时估价器',
    sub: '三步完成。无需先留邮箱 —— 价格区间先出，联系方式后留。',
    stepOf: '第 {n} 步 / 共 3 步',
    chooseService: '您需要什么服务？',
    chooseVolume: '工作量规模',
    contact: '精确报价发送到哪里？',
    services: {
      moving: '搬家服务',
      cleanup: '清洁 + 垃圾清运',
      snow: '铲雪服务',
      yard: '庭院养护',
    },
    movingOptions: [
      { id: '1', label: '一房 / 开间' },
      { id: '2', label: '两房' },
      { id: '3', label: '三房' },
      { id: '4', label: '四房以上 / 办公室' },
    ],
    cleanupOptions: [
      { id: '1', label: '一房 / 开间' },
      { id: '2', label: '两房' },
      { id: '3', label: '三房' },
      { id: '4', label: '四房以上' },
    ],
    snowOptions: [
      { id: 'small', label: '小型车道（1–2辆车）' },
      { id: 'medium', label: '双车位车道 + 步道' },
      { id: 'large', label: '大型地块 / T字路口' },
      { id: 'commercial', label: '商业广场 / 公寓' },
    ],
    yardOptions: [
      { id: 'small', label: '小院（370㎡以下）' },
      { id: 'medium', label: '中院（370–740㎡）' },
      { id: 'large', label: '大院 / 庄园' },
      { id: 'plan', label: '全年维护套餐' },
    ],
    volumeLabel: '请选择规模',
    postalLabel: '邮政编码',
    postalHint: '约克区邮编前缀：L3P、L3R、L4B、L6A…',
    nameLabel: '姓名',
    emailLabel: '电子邮箱',
    phoneLabel: '电话',
    notesLabel: '还有什么需要我们了解的？（选填）',
    next: '继续',
    back: '返回',
    submit: '获取精确报价',
    submitting: '提交中…',
    rangeLabel: '此类工作的一般区间',
    firmQuote: '调度团队将在 2 个工作小时内给您锁定一口价。',
    successTitle: '已收到您的请求。',
    successBody: '报价请求已进入调度队列，2 个工作小时内会与您电话或邮件联系。',
    another: '再估一单',
    disclaimer: '仅为参考区间 —— 最终价格以现场或视频勘察为准。',
    errors: {
      required: '此项为必填',
      email: '请输入有效邮箱',
      phone: '请输入有效电话',
      postal: '格式如 L6A 1A1',
      outside: '超出约克区范围 —— 我们或许仍可服务，提交后确认。',
    },
    step2Title: '定制服务与增值选项',
    step2Sub: '根据您的物业情况选择配置 —— 价格即时联动刷新',
    step3Title: '预约日期与联系方式',
    step3Sub: '我们将在此处向您发送确认方案与锁定报价',
    dateLabel: '期望服务日期',
    dateHint: '选择日期',
    urgencyLabel: '时间紧迫度',
    urgencyOptions: {
      flexible: '时间灵活（常规排期）',
      rush: '月底 / 周末交房高峰期',
      urgent: '紧急服务（24–48小时内极速响应）',
    },
    destPostalLabel: '目的地邮编（搬入地址）',
    destPostalHint: '例如 L4B 3M2（大多伦多 / 约克区）',
    moveTypeTitle: '服务形式',
    moveTypes: {
      full: '全包搬家（专属卡车 + 专业搬运团队）',
      labour: '仅出人工（搬运装卸自带卡车或Pod）[-$120]',
    },
    accessTitle: '进出条件与房屋类型',
    accessTypes: {
      ground: '地面平层 / 车道直达（+$0）',
      elevator: '公寓大楼 / 预约电梯时段（+$60）',
      stairs: '2–3层联排镇屋 / 楼梯较多（+$50）',
    },
    movingAddonsTitle: '特重物品与专业保护（选填）',
    movingAddons: {
      piano: '立式钢琴 / 重型保险箱 / 健身器械（+$180）',
      disassembly: '床架与大型家具拆装（+$75）',
      packing: '床垫专业防尘袋与衣物挂箱（+$45）',
    },
    bathroomsTitle: '卫生间数量',
    bathOptions: [
      { id: '1', label: '1 个卫生间（+$0）' },
      { id: '2', label: '2 个卫生间（+$60）' },
      { id: '3', label: '3 个卫生间（+$120）' },
      { id: '4', label: '4 个及以上（+$180）' },
    ],
    conditionTitle: '清洁强度与房屋现状',
    conditionTypes: {
      standard: '标准交房/退租深度清洁（+$0）',
      heavy: '装修后除尘 / 宠物毛发重度油污（+$95）',
    },
    cleaningAddonsTitle: '厨房电器与玻璃深度选配（选填）',
    cleaningAddons: {
      oven: '烤箱内部重油污深度除焦（+$50）',
      fridge: '冰箱内部深度清洁消毒（+$45）',
      windows: '室内窗户玻璃与轨道清洁（+$65）',
      carpet: '地毯专业蒸汽抽洗（+$85）',
    },
    junkTitle: '垃圾清运杂物体积',
    junkOptions: [
      { id: 'none', label: '无需清运垃圾 —— 仅清洁（+$0）' },
      { id: 'light', label: '少量（1–2件旧家具 / 旧床垫）（+$120）' },
      { id: 'medium', label: '半拖斗 / 1个房间杂物清空（+$260）' },
      { id: 'heavy', label: '全屋清理 / 地下室车库彻底清空（+$480）' },
    ],
    snowTypeTitle: '铲雪服务周期',
    snowTypes: {
      seasonal: '包季畅享（11月15日至4月1日，积雪>5cm自动触发）',
      per_visit: '单次风暴紧急清雪',
    },
    snowAddonsTitle: '加拿大冬季安全增选（选填）',
    snowAddons: {
      walkway: '人工清理门前走道、台阶与前廊（包季+$120 / 单次+$35）',
      ecoSalt: '宠物安全与混凝土防护环保盐（包季+$80 / 单次+$25）',
      iceScrape: '坚冰人工刮除破冰服务（+$45）',
    },
    yardPackagesTitle: '安省热门季节性维护（可多选）',
    yardPackages: {
      aeration: '春季打孔透气、除枯草与动力耙草（+$140）',
      mow: '双周规律剪草修边套餐（5–10月）（+$45/次）',
      leaves: '秋季落叶彻底清扫与装袋路边清运（+$160）',
      hedges: '雪松树篱与灌木精细修剪（+$120）',
      gutters: '屋檐排水槽（天沟）落叶清理防冻冲洗（+$150）',
    },
    trackRequestBtn: '实时查看订单追踪 →',
    trackHint: '您可以随时查看调度派单与师傅实时位置。',
    selectService: '请先选择服务',
    selectVolume: '请先选择规模',
  },

  gallery: {
    eyebrow: '作业实拍',
    title: '前后对比',
    sub: '拖动滑块 —— 来自万锦及约克区真实作业记录。',
    cases: [
      { title: '于比弗溪遗产房屋清运', before: '前 —— 两拖斗杂物', after: '后 —— 打扫干净' },
      { title: '万锦装修后清洁', before: '前 —— 石膏粉尘', after: '后 —— 交房标准' },
      { title: '旺市商业停车场', before: '前 —— 积雪14厘米', after: '后 —— 早5:30撒盐完毕' },
    ],
  },
  reviews: {
    eyebrow: '300+ 评价，平均 4.9 / 5',
    title: '业主与物业管理的选择',
    items: [
      {
        quote: '团队八点整到达，家具全部包裹保护，交房清洁一次通过验收。他们已经进入我们的长期供应商名单。',
        name: 'D. Whitfield',
        role: '物业管理经理，康山',
      },
      {
        quote: '地下室杂物中午前全部清空 —— 两拖斗，墙面无损伤，连车库都扫了。价格公道，全程省心。',
        name: 'M. Chen',
        role: '业主，万锦',
      },
      {
        quote: '周末帮我们完成办公室搬迁，周一早上 40 个工位全部就绪。这就够了。',
        name: 'S. Okafor',
        role: '运营负责人，旺市',
      },
    ],
  },
  dualCta: {
    residentialTitle: '家庭客户',
    residentialBody: '一口价搬家、清洁与季节套餐。60秒出参考价，2个工作小时内锁定精确报价。',
    residentialCta: '住宅即时估价',
    commercialTitle: '物业公司与企业客户',
    commercialBody: '供应商账户：保险证书（COI）备档、WSIB 合规、暴雪优先响应、组合物业月度合并账单。',
    commercialCta: '发起商业合作（RFP）',
    commercialNote: '欢迎组合物业铲雪与绿化年度合同。',
  },
  areas: {
    eyebrow: '调度中心：万锦',
    title: '约克区全域服务',
    sub: '主城区 90 分钟内紧急响应。北约克和士嘉堡交界社区亦可安排。',
    stats: { drive: '分钟平均调度', jobs: '完成订单', fsa: '覆盖邮编前缀' },
    viewPage: '查看城市页面',
  },
  footer: {
    tagline: '万锦及约克区搬家、清洁与物业维护服务。用专业服务，让生活更轻松。',
    servicesTitle: '服务项目',
    areasTitle: '服务区域',
    contactTitle: '联系方式',
    hoursLabel: '营业时间',
    rights: '版权所有。',
    licensed: '持证全保险运营 · CVOR 认证车队',
  },
};
